import type { NextPage } from 'next'
import React, {useEffect, useState} from 'react'
import Head from 'next/head'
import {TweenMax, gsap} from 'gsap'
import * as THREE from "three"
import {GLTFLoader} from 'three/examples/jsm/loaders/GLTFLoader'
import { TextureLoader } from 'three'
import {OrbitControls} from "three/examples/jsm/controls/OrbitControls"
import LoadingScene from './components/LoadingScene'

import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  const [loading, setLoading] = useState(false)
  const [viewport, setViewPort] = useState({width:0, height:0, aspectRatio:1})
  const [viewSize, setViewSize] = useState({distance:3, vFov:0, height:1, width:1})
  const [cursorPos, setPosition] = useState({x:0, y:0})
  let mouse = new THREE.Vector2() 
  let camera: any
  let container: any
  let scene = new THREE.Scene()
  setTimeout(() => {
    if(typeof document !== "undefined"){
      const target1 = document.getElementById('loadingRender')
      gsap.to(target1, 2, {opacity:0})
      const target2 = document.getElementById('content')
      gsap.to(target2, 2, {opacity:1})
    }
  }, 4000);  
  const webGLRender = () => {
    container = document.getElementById('webGLRender')
    const renderer = new THREE.WebGLRenderer({antialias: true, alpha: true });
    container.appendChild( renderer.domElement )
    const viewport = { width : container.clientWidth, height : container.clientHeight, aspectRatio : container.clientWidth / container.clientHeight}    
    camera = new THREE.PerspectiveCamera( 75, viewport.aspectRatio, 0.1, 100000 )
    const viewSize = { distance : camera.position.z, vFov : (camera.fov * Math.PI) / 180, height : 2 * Math.tan((camera.fov * Math.PI) / 180 / 2) * camera.position.z, width : 2 * Math.tan((camera.fov * Math.PI) / 180 / 2) * camera.position.z * viewport.aspectRatio, }
    camera.position.set(0, 150, 800)
    const controls = new OrbitControls( camera, renderer.domElement );
    controls.enableRotate = true;
    controls.update();

    setViewPort(viewport)
    setViewSize(viewSize)
    renderer.setClearColor('#000000', 0.1)
    renderer.setSize(viewport.width, viewport.height)
    renderer.setPixelRatio(window.devicePixelRatio)
    
    animate();
    function animate() {
      requestAnimationFrame( animate );
      renderer.render( scene, camera );
    }
    window.scrollTo({ top: 0, behavior: 'smooth' })

    window.addEventListener( 'resize', onWindowResize )
    function onWindowResize() {    
      container = document.getElementById('webGLRender')
      if(container){
      
      camera.aspect = container.clientWidth / container.clientHeight;
      camera.updateProjectionMatrix();
      
      }
      setViewPort(viewport)
      setViewSize(viewSize)
      renderer.setSize( container.clientWidth , container.clientHeight );
    }
  }

  useEffect(() => {
    if(typeof document !== "undefined"){
      webGLRender()
    }
  }, [])

    
  return (
    <div className={styles.container}>
      <Head>
        <title>77 Media Holding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/default-favicon.ico" />
      </Head>
      <main className={styles.main}>
      
        <div id='loadingRender' className='absolute top-0 left-0 w-full h-[100vh] z-10' style={{opacity:1}}>
          <LoadingScene/>
        </div>
        <div id='content' className='w-full h-full text-[90px] text-white text-center' style={{opacity:0}}>
          <div>
            Company page
          </div>
        </div>
      </main>

      <div id='webGLRender' className='fixed w-full h-full top-0 left-0 pointer-events-none z-0'/>
    </div>
  )
}

export default Home