import type { NextPage } from 'next'
import React, {useEffect, useState} from 'react'
import Head from 'next/head'
import LoadingScene from './components/LoadingScene'
import styles from '../styles/Home.module.scss'

const Home: NextPage = () => {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>77 Media Holding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/default-favicon.ico" />
      </Head>
      <div className='relative top-0 left-0 w-full h-[100vh]'>
        <LoadingScene/>
      </div>
    </div>
  )
}

export default Home